In [1]:
import pandas as pd
import numpy as np
import pickle
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sna
import sklearn
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import RandomizedSearchCV
import imblearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score

C:\Users\GOJO\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\GOJO\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\Users\GOJO\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
import os
os.getcwd()

'C:\\Users\\GOJO\\Documents\\Personal_Loan_Prediction_Approval (Machine Learning )\\Training'

In [3]:
Data = pd.read_csv(r"C:\\Users\\GOJO\\Documents\\Personal_Loan_Prediction_Approval (Machine Learning )\\DataSet\\testData1.csv")

In [4]:
Data.head()

Loan_ID Gender Married Dependents     Education Self_Employed   
0  LP001015   Male     Yes          0      Graduate            No  \
1  LP001022   Male     Yes          1      Graduate            No   
2  LP001031   Male     Yes          2      Graduate            No   
3  LP001035   Male     Yes          2      Graduate            No   
4  LP001051   Male      No          0  Not Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term   
0             5720                  0       110.0             360.0  \
1             3076               1500       126.0             360.0   
2             5000               1800       208.0             360.0   
3             2340               2546       100.0             360.0   
4             3276                  0        78.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban         yes  
1             1.0         Urban         yes  
2             1.0         Urban         yes  
3             NaN         Urban          no  
4             1.0         Urban         yes

In [5]:
Data.isnull().sum()

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
Loan_Status           0
dtype: int64

In [6]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            367 non-null    object 
 1   Gender             356 non-null    object 
 2   Married            367 non-null    object 
 3   Dependents         357 non-null    object 
 4   Education          367 non-null    object 
 5   Self_Employed      344 non-null    object 
 6   ApplicantIncome    367 non-null    int64  
 7   CoapplicantIncome  367 non-null    int64  
 8   LoanAmount         362 non-null    float64
 9   Loan_Amount_Term   361 non-null    float64
 10  Credit_History     338 non-null    float64
 11  Property_Area      367 non-null    object 
 12  Loan_Status        367 non-null    object 
dtypes: float64(3), int64(2), object(8)
memory usage: 37.4+ KB


In [7]:
Data['Gender'] = Data['Gender'].fillna(Data['Gender'].mode()[0])
Data['Dependents'] = Data['Dependents'].str.replace('+','')
Data['Dependents'] = Data['Dependents'].fillna(Data['Dependents'].mode()[0])
Data['Self_Employed'] = Data['Self_Employed'].fillna(Data['Self_Employed'].mode()[0])
Data['LoanAmount'] = Data['LoanAmount'].fillna(Data['LoanAmount'].mode()[0])
Data['Loan_Amount_Term'] = Data['Loan_Amount_Term'].fillna(Data['Loan_Amount_Term'].mode()[0])
Data['Credit_History'] = Data['Credit_History'].fillna(Data['Credit_History'].mode()[0])
Data['Married'] = Data['Married'].fillna(Data['Married'].mode()[0])

In [8]:
Data.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [9]:
Data['LoanAmount']=Data['LoanAmount'].astype('int64')

Data['Loan_Amount_Term']=Data['Loan_Amount_Term'].astype('int64')

Data['Credit_History']=Data['Credit_History'].astype('int64')


In [10]:
from imblearn.combine import SMOTETomek
smote = SMOTETomek()

In [12]:
x = Data.iloc[:,1:11].values
y = Data.iloc[:,-1].values


In [13]:
Gen = Data.iloc[:,1].values
Ed = Data.loc[:,['Education']]

AI = Data.loc[:,['ApplicantIncome']]
CH = Data.loc[:,['Credit_History']]

Ma = Data.loc[:,['Married']]
SE = Data.loc[:,['Self_Employed']]
LA = Data.loc[:,['LoanAmount']]
PA = Data.loc[:,['Property_Area']]

In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Gen = le.fit_transform(Gen)
Ma = le.fit_transform(Ma)
SE = le.fit_transform(SE)
PA = le.fit_transform(PA)
Ed = le.fit_transform(Ed)


C:\Users\GOJO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\GOJO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\GOJO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\GOJO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_label.py:11

In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [1])], remainder= 'passthrough')
x = np.array(ct.fit_transform(x))
x

array([[0.0, 1.0, 1, ..., 52, 10, 1],
       [0.0, 1.0, 1, ..., 67, 10, 1],
       [0.0, 1.0, 1, ..., 119, 10, 1],
       ...,
       [1.0, 0.0, 1, ..., 67, 10, 1],
       [0.0, 1.0, 1, ..., 94, 10, 1],
       [1.0, 0.0, 1, ..., 40, 6, 1]], dtype=object)

In [18]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,0] = le.fit_transform(x[:,0])
x[:,1] = le.fit_transform(x[:,1])
x[:,2] = le.fit_transform(x[:,2])
x[:,3] = le.fit_transform(x[:,3])
x[:,4] = le.fit_transform(x[:,4])
x[:,5] = le.fit_transform(x[:,5])
x[:,6] = le.fit_transform(x[:,6])
x[:,7] = le.fit_transform(x[:,7])
x[:,8] = le.fit_transform(x[:,8])
x[:,9] = le.fit_transform(x[:,9])
x[:,10] = le.fit_transform(x[:,10])
x


array([[0, 1, 1, ..., 52, 10, 1],
       [0, 1, 1, ..., 67, 10, 1],
       [0, 1, 1, ..., 119, 10, 1],
       ...,
       [1, 0, 1, ..., 67, 10, 1],
       [0, 1, 1, ..., 94, 10, 1],
       [1, 0, 1, ..., 40, 6, 1]], dtype=object)

In [62]:
x=x.astype('int32')
#x=x.astype('float32')
y = le.fit_transform(y)
y.shape[0]
x.shape[0]




array([[  0,   1,   1, ...,  52,  10,   1],
       [  0,   1,   1, ...,  67,  10,   1],
       [  0,   1,   1, ..., 119,  10,   1],
       ...,
       [  1,   0,   1, ...,  67,  10,   1],
       [  0,   1,   1, ...,  94,  10,   1],
       [  1,   0,   1, ...,  40,   6,   1]])

In [41]:
x_bal,y_bal = smote.fit_resample(x,y)

In [63]:
sc = StandardScaler()


In [64]:
X_train, X_test, y_train, y_test = train_test_split(
x_bal, y_bal, test_size=0.33, random_state=42)


In [65]:
def decisionTree(X_train, X_test, y_train, y_test):
    dt=DecisionTreeClassifier()
    dt.fit(X_train,y_train)
    yPred= dt.predict(X_test)
    print('***DecisionTreeClassifier***')
    print('Confusion matrix')
    print(confusion_matrix(y_test,yPred))
    print('Classification report')
    print(classification_report(y_test,yPred))
    

In [66]:
def randomForest(X_train,X_test,y_train,y_test):
    rf = RandomForestClassifier()
    rf.fit(X_train,y_train)
    yPred = rf.predict(X_test)
    print('******RandomForestClassifier*****')
    print('Confusion matrix')
    print(confusion_matrix(y_test,yPred))
    print('Classification report')
    print(classification_report(y_test,yPred))
    

In [67]:
def KNN(X_train,X_test,y_train,y_test):
    Knn = KNeighborsClassifier()
    Knn.fit(X_train,y_train)
    yPred = Knn.predict(X_test)
    print('******KNeighborsClassifier*****')
    print('Confusion matrix')
    print(confusion_matrix(y_test,yPred))
    print('Classification report')
    print(classification_report(y_test,yPred))
    

In [68]:
def xgboost(X_train,X_test,y_train,y_test):
    xg = GradiantBoostingClassifier()
    xg.fit(X_train,y_train)
    yPred = xg.predict(X_test)
    print('******GradiantBoostingClassifier*****')
    print('Confusion matrix')
    print(confusion_matrix(y_test,yPred))
    print('Classification report')
    print(classification_report(y_test,yPred))
    

In [69]:
import tensorflow 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


In [70]:
classifier = Sequential()
classifier.add(Dense(units=100, activation='relu', input_dim=11))


In [71]:
classifier.add(Dense(units=50, activation='relu'))

In [72]:
classifier.add(Dense(units=1, activation='sigmoid'))


In [73]:
classifier.compile(
    optimizer = 'adam',
    loss = 'binary_crossentropy',
    metrics = ['accuracy'])


In [74]:
classifier.fit(X_train,
              y_train,
              batch_size= 32,
              epochs=100)

Epoch 1/100
11/11 [==============================] - 3s 10ms/step - loss: 1.3520 - accuracy: 0.5105
Epoch 2/100
11/11 [==============================] - 0s 14ms/step - loss: 1.2279 - accuracy: 0.5255
Epoch 3/100
11/11 [==============================] - 0s 12ms/step - loss: 0.9285 - accuracy: 0.6006
Epoch 4/100
11/11 [==============================] - 0s 10ms/step - loss: 0.7969 - accuracy: 0.5465
Epoch 5/100
11/11 [==============================] - 0s 12ms/step - loss: 0.6750 - accuracy: 0.6246
Epoch 6/100
11/11 [==============================] - 0s 9ms/step - loss: 0.6758 - accuracy: 0.6366
Epoch 7/100
11/11 [==============================] - 0s 13ms/step - loss: 0.8271 - accuracy: 0.5766
Epoch 8/100
11/11 [==============================] - 0s 12ms/step - loss: 0.6741 - accuracy: 0.6276
Epoch 9/100
11/11 [==============================] - 0s 13ms/step - loss: 0.5934 - accuracy: 0.6787
Epoch 10/100
11/11 [==============================] - 0s 10ms/step - loss: 0.5858 - accuracy: 0.6757


11/11 [==============================] - 0s 8ms/step - loss: 0.3160 - accuracy: 0.8709
Epoch 83/100
11/11 [==============================] - 0s 8ms/step - loss: 0.3630 - accuracy: 0.8619
Epoch 84/100
11/11 [==============================] - 0s 8ms/step - loss: 0.2840 - accuracy: 0.8949
Epoch 85/100
11/11 [==============================] - 0s 8ms/step - loss: 0.2987 - accuracy: 0.8709
Epoch 86/100
11/11 [==============================] - 0s 8ms/step - loss: 0.3569 - accuracy: 0.8198
Epoch 87/100
11/11 [==============================] - 0s 8ms/step - loss: 0.2944 - accuracy: 0.8979
Epoch 88/100
11/11 [==============================] - 0s 8ms/step - loss: 0.2661 - accuracy: 0.9249
Epoch 89/100
11/11 [==============================] - 0s 9ms/step - loss: 0.2735 - accuracy: 0.9039
Epoch 90/100
11/11 [==============================] - 0s 8ms/step - loss: 0.2536 - accuracy: 0.9189
Epoch 91/100
11/11 [==============================] - 0s 8ms/step - loss: 0.2567 - accuracy: 0.9189
Epoch 92/100


In [75]:
print(classifier.predict([[1,1, 0,1,1,4276, 1542, 154, 240,0, 1]]))

1/1 [==============================] - 0s 238ms/step
[[1.]]


In [76]:
classifier.save("loan1.h5")

In [77]:
y_pred = classifier.predict(X_test)

6/6 [==============================] - 1s 16ms/step


In [78]:
y_pred

array([[2.9703051e-01],
       [8.2322997e-01],
       [1.0938784e-03],
       [6.3614309e-02],
       [5.9529882e-02],
       [1.6019154e-01],
       [7.1787703e-01],
       [6.0024297e-01],
       [2.7392784e-02],
       [8.5561705e-01],
       [9.6664947e-01],
       [1.9500615e-01],
       [8.8807344e-03],
       [9.6286917e-01],
       [6.3997680e-01],
       [1.6679084e-01],
       [6.4422387e-01],
       [8.0529243e-01],
       [7.6298624e-01],
       [2.3362905e-01],
       [9.1459233e-01],
       [2.6261572e-05],
       [3.5134245e-02],
       [7.4738771e-01],
       [2.1856809e-01],
       [8.8818955e-01],
       [2.8810993e-02],
       [4.6801108e-01],
       [6.0027134e-02],
       [9.3141842e-01],
       [1.6287512e-01],
       [9.1382933e-01],
       [3.7639126e-02],
       [9.6023643e-01],
       [1.6833453e-02],
       [9.6164995e-01],
       [4.0216997e-04],
       [8.2169074e-01],
       [9.3860060e-02],
       [9.9872261e-01],
       [5.3225911e-01],
       [2.529098